services:

  menu-app:
    build:
      context: .
    container_name: menu-app
    depends_on:
      - database
    ports:
      - "8000:8000"

  database:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=menu_db
    ports:
      - "5432:5432"
