version: "3.8"

services:

  menu-app:
    build:
      context: .
    container_name: menu-app
    volumes:
      - ./:/code
    environment:
      DB_URL: "postgresql://dbuser:pass@database:5432/menu_db"
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8000:8000"

  database:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: dbuser
      PGUSER: dbuser
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: menu_db
    volumes:
      - pg_database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -h database"
      interval: 2s
      timeout: 30s
      retries: 5
      start_period: 80s

volumes:
  pg_database:
